# The random module

In [1]:
import random

a = random.random()    # random float in [0,1)
print(a)

0.15667788465951293


In [5]:

a = random.uniform(1,10)    # random float in range between 1 and 10
print(a)

2.4259297528863963


In [9]:
a = random.randint(1,10)    # random integer in range [a,b]. b is included
print(a)

6


In [15]:
a = random.randrange(1,20)    # random integer in range between 1 and 20. Note: 20 is excluded
print(a)

13


In [16]:
# random float from a normal distribution with mu and sigma
a = random.normalvariate(0, 1)
print(a)

-0.914525049948841


In [17]:
mylist = list("ABCDEFGH")
print(mylist)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']


In [20]:
# choose a random element from a sequence
a = random.choice(list("ABCDEFGHI"))
print(a)

A


In [21]:
# choose k unique random elements from a sequence
a = random.sample(list("ABCDEFGHI"), 3)
print(a)

['H', 'I', 'E']


In [22]:
# choose k elements with replacement, and return k sized list
a = random.choices(list("ABCDEFGHI"),k=3)
print(a)

['G', 'H', 'A']


In [23]:
# shuffle list in place
a = list("ABCDEFGHI")
random.shuffle(a)
print(a)

['F', 'C', 'G', 'B', 'A', 'E', 'H', 'D', 'I']


# The seed generator

In [24]:
import random

random.seed(1)
mylist = list("ABCDEFGH")
random.shuffle(mylist)
print(mylist)

['D', 'G', 'B', 'F', 'H', 'A', 'E', 'C']


In [28]:
import random

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.13436424411240122
2
0.13436424411240122
2


In [29]:
import random

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

random.seed(3)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1
0.23796462709189137
9


In [ ]:
print('Seeding with 1...\n')

random.seed(1)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 1...\n')
random.seed(1)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

# The secrets module

In [31]:
import secrets

a = secrets.randbelow(10)    # random integer in range [0, 10). Note: 10 is excluded.
print(a)

3


In [40]:
a = secrets.randbits(5)    # return an integer with k random bits.
print(a)

10


In [41]:
a = secrets.choice(list("ABCDEFGHI"))    # choose a random element from a sequence
print(a)

I


# Random numbers with NumPy

In [43]:
import numpy as np

a = np.random.randint(0,10,(3,4))
print(a)

[[0 8 8 0]
 [4 6 4 2]
 [9 8 5 1]]


In [45]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
np.random.shuffle(arr)    # only switch rows
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [50]:
import numpy as np

np.random.seed(1)
# rand(d0,d1,…,dn)
# generate nd array with random floats, arrays has size (d0,d1,…,dn)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [51]:
# reset the seed
np.random.seed(1)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [52]:
# generate nd array with random integers in range [a,b) with size n
values = np.random.randint(0, 10, (5,3))
print(values)

[[5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]
 [2 4 7]]


In [53]:
# generate nd array with Gaussian values, array has size (d0,d1,…,dn)
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
values = np.random.randn(5)
print(values)

[-2.29230928 -1.41555249  0.8858294   0.63190187  0.04026035]


In [54]:
# randomly shuffle a nd array.
# only shuffles the array along the first axis of a multi-dimensional array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.random.shuffle(arr)
print(arr)

[[4 5 6]
 [7 8 9]
 [1 2 3]]
